dynamixels: ['head_pan_joint', 'head_tilt_joint']
controllers: ['head_pan_controller', 'head_tilt_controller']

head_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_tilt_joint
    joint_speed: 4.0
    motor:
        id: 1
        init: 2048
        min: 0 
        max: 4096

head_pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_pan_joint
    joint_speed: 4.0
    motor:
        id: 2
        init: 2048
        min: 0
        max: 4096


